title: Michael Okorocha
logo: https://avatars.githubusercontent.com/u/218065264?v=4
description: CyberSecurity Analyst | Security Operation Center SOC Analyst | Governance Risk Compliance Analyst
ğŸ“ +234 818 509 8798 | +234 803 296 5165
âœ‰ï¸ princecharming24hrs@gmail.com
ğŸ”— linkedin.com/in/michaelokorocha
#show_downloads: true
theme: jekyll-theme-minimal
