
title: Michael Okorocha
logo: https://avatars.githubusercontent.com/u/218065264?v=4
description: CyberSecurity Analyst | SOC Analyst | GRC Analyst
Tel : ğŸ“ +234 818 509 8798
Email: âœ‰ï¸ princecharming24hrs@gmail.com
Link: ğŸ”— linkedin.com/in/michaelokorocha
#show_downloads: true
theme: jekyll-theme-minimal
